### PR TITLE
Add Elixir

### PR DESCRIPTION
**Pull request by ryanwinchester**
ᕕ( ᐛ )ᕗ

### CODE REVIEW

**Comment by emilpriver** [comment]
Hey, Do you want me to add Elixir for the test? 
I can merge if you want :D

**Comment by ryanwinchester** [comment]
I thought it would be fun, but then realized it doesn't really serve any purpose 😅

**Comment by emilpriver** [comment]
Agreed, mby we can keep it for fun :D This test is mostly made out of curiosity and fun. 
I would like to merge this and I do it if you say ok to it @ryanwinchester

**Comment by ryanwinchester** [comment]
Yeah, it's fine

**Comment by emilpriver** [comment]
Many thanks for the contribution! :D

**Pull request merged**
